export const FILTER_DATA_ACTION_STARTED = 'FILTER_DATA_ACTION_STARTED';
export const FILTER_DATA_ACTION_COMPLETED = 'FILTER_DATA_ACTION_COMPLETED';
export const FILTER_DATA_ACTION_FAILED = 'FILTER_DATA_ACTION_FAILED';